### ISSUE TITLE
Reconnecting on same object fails

### ISSUE THREAD

**Issue by jtreanor** [acmacalister/jetfire#13]
On master, reconnecting to the same object seems to be broken.

For example if I create and connect to a new `JFRWebSocket` and some time later call `disconnect`, any attempt to call `connect` on that same object will fail.

This seems to be a regression since 0.1.2.

On a related note, I think it may be a good idea for all calls to `websocketDidDisconnect:error:` to be centralized so that the websocket connect is always cleaned up. The current behaviour is confusing as the delegate can get multiple `websocketDidDisconnect:error:` calls (for example if I receive an "Invalid HTTP upgrade" error, `isConnected` is still true and a few seconds later `websocketDidDisconnect:error:` is called again).

**Comment by acmacalister** [comment]
Thanks for the report, I'll take a look. I haven't had a chance to completely test out the additions I did in master, which is why I haven't pushed a tag to cocoapods yet. :smile:

**Comment by jtreanor** [comment]
Thanks @acmacalister. One point to add here, I was testing the repo at ea1da03f957d4c0ece223b7dfc6348f31205d353, so it was introduced sometime before then.

**Comment by acmacalister** [comment]
@jtreanor. Sorry for the delay. I had a chance to test this and checked a change into master that I think might help. Can you try it out on your end?

**Comment by jtreanor** [comment]
Thanks for that, I'll check it out!

**Comment by jtreanor** [comment]
Sorry for the delay @acmacalister. This change stops some unexpected behaviour but the problem of ambiguous connection state causes a problem here.

There is no guarantee that when `websocketDidDisconnect:error:` is called that `_isConnected` will be `NO`, so the problem still exists. At least for now, I am recreating objects rather than attempting to reconnect to the same object.

**Comment by acmacalister** [comment]
@jtreanor, sorry for not getting back to you until now. Are you still running into the issue with reconnecting to the same object?

**Comment by doctordbx** [comment]
I too am experiencing the socket.connected = YES on the disconnect delegate method.

For the time being I'm just catching this in my code (I am using the socket in a singleton to expose it to a wide array of API calls... although early days) and recreating the socket object if required once it has been flagged as disconnected.

Great work on the library though, was able to get up and running very quickly with it.

**Comment by acmacalister** [comment]
I think 0.1.4 update should take care of this.
