### ISSUE TITLE
Adopt a style guide

### ISSUE THREAD

**Issue by adamkaplan** [acmacalister/jetfire#21]
What are your thoughts on adopting a style guide for this project?

At Yahoo we typically recommend these:
[Apple's Coding Guidelines for Cocoa](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/CodingGuidelines.html)
[NYTimes Objective C Style Guidelines](https://github.com/NYTimes/objective-c-style-guide)

Along with some project-specific guidance.

**Comment by acmacalister** [comment]
I agree a style guide definitely be good. We generally try to stick with the Cocoa conventions, but some of our old C habits crop up now and again. :smile: I like pretty much everything in the NYTimes style guide, save using spaces over tabs and I don't mind that the else statement are on the same line as the closing if brace like so:

```objc
if(something) {
    // do something awesome.
} else {
    // do some other awesome stuff.
}
```

The comment lines breaking each method is something we did again from our C days. Seemed to help with readability when writing longer functions. We can probably just update the contributing guidelines to reflect those differences. wtdy?

**Comment by adamkaplan** [comment]
I do like `else` on a new line – at least right now – but I do waffle on that one. The comments help for sure, and I like to add a newline when there is an `else if` since it can get quite crowded with another conditional brand:

```
if(something) {
    // do something awesome.
} else if (!someComplexStatementHere) {
    // do some other awesome stuff.
} else {
    // do some other awesome stuff.
}```

**Comment by acmacalister** [comment]
agreed. I say we go with your second example as I like newline. I will update the guide accordingly.
