### ISSUE TITLE
Feature Request, Pings

### ISSUE THREAD

**Issue by jojojames** [acmacalister/jetfire#28]
I'd like to request being able to use Pings to a server and having the server send a Pong back. 

We'd then be able to handle the Pong with a callback.

https://github.com/koush/AndroidAsync
https://github.com/square/SocketRocket

I think both of these libraries support being able to use Pings.

**Comment by adamkaplan** [comment]
This is a good idea, not too difficult to do.

The client should be responsible for maintaining the ping-pong stack though, which adds – at least conceptually – friction because not receiving a matching `pong` reply is a protocol-level issue. Just something to consider.

**Comment by acmacalister** [comment]
@adamkaplan agreed. If I remember correctly it has already been added to Starscream, so should be an easy port.

**Comment by jojojames** [comment]
Sounds great.

I think AndroidAsync and SocketRocket also pushes the ping-pong stack maintenance to the client.

**Comment by acmacalister** [comment]
Added in 0.1.4

**Comment by jojojames** [comment]
Cheers.
