### ISSUE TITLE
Weird performance issues

### ISSUE THREAD

**Issue by arietis** [acmacalister/jetfire#29]
I'm getting weird performance issues when trying to connect to the host. In case if it's unsuccessful, i'm reconnecting and here is the screenshot of profiler log.
https://www.dropbox.com/s/efz3r1g8d0ezjq3/Screen%20Shot%202015-06-11%20at%2018.28.29.png?dl=0
Shouldn't worker thread stop when attempt is unsuccessful?

**Comment by daltoniam** [comment]
It will be taken off the runloop once the NSStream delegate reports back the connection is unsuccessful. You are attempting to reconnect every time it fails to connect to the host? Are you getting the `webSocketDidDisconnect:` delegate calls?

**Comment by arietis** [comment]
Hello!
I do get webSocketDidDisconnect: calls. Here is the screenshot of case with empty webSocketDidDisconnect delegate method implementation. https://www.dropbox.com/s/kw7z14ptaideuue/Screenshot%202015-06-15%2013.06.21.png?dl=0

**Comment by daltoniam** [comment]
Interesting. I would add some logging and make sure the `isRunLoop` is getting set to NO.

https://github.com/acmacalister/jetfire/blob/master/JFRWebSocket.m#L307
https://github.com/acmacalister/jetfire/blob/master/JFRWebSocket.m#L258

If the `isRunLoop` gets set to NO, then the thread should stop shortly afterwards.

**Comment by maxydey** [comment]
Hey, getting same issue.
[JFRWebSocket stream:handleEvent:] is being called, there isRunLoop = NO  there, but in 
    while (self.isRunLoop)
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate distantFuture]];

isRunLoop is still 'YES' and it executes forever

**Comment by maxydey** [comment]
Fixed it by switching strings :

    self.isRunLoop = YES;
    [self.outputStream write:[data bytes] maxLength:[data length]];

Otherwise disconnectStream: is being called before self.isRunLoop = YES, so it has no chance to be setted back to NO.

**Comment by daltoniam** [comment]
@maxydey nice find, I could have swore I already change that, must have done it in Starscream. I will change that shortly, thanks!

**Comment by BarryHaanstra** [comment]
It would be nice if you could make a new tag / release for CocoaPods. Right now you get 0.1.2 from Jan 8, which does not include this fix.

**Comment by acmacalister** [comment]
@BarryHaanstra, I will update it today.

**Comment by acmacalister** [comment]
I think 0.1.4 update should take care of this.
