### ISSUE TITLE
Crash in JFRWebSocket.m in version 0.1.4

### ISSUE THREAD

**Issue by mmackowiak** [acmacalister/jetfire#35]
Hello!

For some time, about 2 weeks, we experience random crashes happening on app startup, while WS attempts to connect to server. Seems change in this place was introduced in this commit: https://github.com/acmacalister/jetfire/commit/ae6d6559da096c29d4a300dc5a2ae1460f76e433.

Unfortunately, we haven't found any way to reliably reproduce the issue, it seems to happen randomly. I attach screenshot with as much data, as we were able to collect. This particular one comes from iPhone 5c and jetfire 0.1.4.

<img width="1279" alt="zrzut ekranu 2015-09-15 o 09 04 28" src="https://cloud.githubusercontent.com/assets/1244595/9876984/5204bc36-5bba-11e5-96b4-e77c0407509c.png">

Thanks for help!

**Comment by daltoniam** [comment]
I just checked in what I think should fix the issue. Let me know if that does fix it and I will push out a new tag/release.

**Comment by mmackowiak** [comment]
Thank you very much for your help! We'll check it out after current version is released - temporarily we switched to more stable 0.1.2.

**Comment by daltoniam** [comment]
:+1:
