### ISSUE TITLE
Problems compiling for iOS 7

### ISSUE THREAD

**Issue by Sheepow** [acmacalister/jetfire#40]
Good day.
I'm trying to use jet fire 0.1.5 on a project using iOS 7, but it won't let me do that, it highlights syntax errors on both JFRSecurity .h and .m files. I thought it supported iOS 7 and above.

Should I stick with 0.1.4?

**Comment by acmacalister** [comment]
We intend for it to still work on iOS 7, but we might have used an iOS 8+ API for the SSL pinning by mistake. I will look into to see what we can do.

**Comment by kevinrenskers** [comment]
Any news on this?

**Comment by acmacalister** [comment]
Not yet. Hopefully I can look at this week when I move some of the Starscream fixes over.

**Comment by Cloudef** [comment]
https://github.com/acmacalister/jetfire/pull/49/commits/26d2cd2277946c0a3191a71f59611a8b10854d1f#diff-7522e50e7a330f1fc27131f9f173feaaR120 may be relevant
