### ISSUE TITLE
How to reconnect？

### ISSUE THREAD

**Issue by Niue** [acmacalister/jetfire#42]
“ -(void)websocketDidDisconnect:(JFRWebSocket*)socket error:(NSError*)error {
    NSLog(@"websocket is disconnected: %@", [error localizedDescription]);
        [self.socket connect];
}” 
I perform the above methods , but "self.isCreated"  is NO. how to reconnect?

**Comment by acmacalister** [comment]
I'm not sure what issue you are running into. `self.isCreated` is an internal property and shouldn't affect the public API. Are you having an issue reconnecting when the client gets disconnected?
