### ISSUE TITLE
The server sends massive packets.

### ISSUE THREAD

**Issue by netmaid** [acmacalister/jetfire#44]
When the server send massive packets to the client, main thread has stuck for dispatching delegation in the below codes.

https://github.com/acmacalister/jetfire/blob/0.1.5/JFRWebSocket.m#L611-L619
https://github.com/acmacalister/jetfire/blob/0.1.5/JFRWebSocket.m#L621-L629

I've removed dispatch_async() and received packet pooling on onText, and fire delegation using NSTimer. 

What do you think about this scenario?

**Comment by acmacalister** [comment]
I could see how that would be a problem. I would suggest using a custom queue and dispatching to the main thread when you are ready. See this in the docs:

https://github.com/acmacalister/jetfire#custom-queue-1
