### ISSUE TITLE
websocket is disconnected: 

### ISSUE THREAD

**Issue by syedrazackimran** [acmacalister/jetfire#60]
Hi, I need a help.. i'm trying to implement socket for obj-c but i'm facing below issues .. same IP and Port i try to implement on swift socket.io its connect ,.. but obj-c its return disconnected .. i don't know why kindly do needful .. they are using socket >v1.0 is it support for that version 

urlRequest = "<CFHTTPMessageRef 0x600000169240(0x600000169250)> { GET request, url http://192.168.17.7:5000 }"
 
websocket is disconnected: (null)

**Comment by Supertecnoboff** [comment]
I have the exact same issue too. @acmacalister do you know what is wrong?

**Comment by Supertecnoboff** [comment]
Ok I was having same issue, but I managed to fix it. Firstly I was trying to use this library with the Twitter Streaming API.... which doesn't support sockets..... great start!

But secondly I ended up using ```NSURLSession``` and its associated delegate methods, to setup and load in the continuous stream of data, from the Twitter API. Works perfectly and is incredibly easy to setup. I would recommend looking into it, if you still haven't got this working. Here is an example:

Set the delegate in your header: ```<NSURLSessionDelegate>```

Create the URL request/session objects:

```
// Set the stream session.
NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration delegate:self delegateQueue:nil];
               
// Start the data stream.
[[session dataTaskWithRequest:request] resume];
```

Finally setup the delegate methods:
```
-(void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveData:(NSData *)data {
    
    NSError *feedError = nil;
    NSDictionary *feed = [NSJSONSerialization JSONObjectWithData:data options:0 error:&feedError];
    NSLog(@"%@", feed);
}

-(void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error {
    
    if (error) {
        NSLog(@"%@", error);
    }
}
```

That's it! Now all you have to do is to parse the data returned in the ```feed``` dictionary and update your UI accordingly.

**Comment by acmacalister** [comment]
I'm not sure how to help on this. Websockets != Socket and definitely != Socket.io. If you working with Socket.io you would need to use a wrapper library or use Jetfire as a base implementation for the Websocket of Socket.io.
