### ISSUE TITLE
Xcode warning thrown

### ISSUE THREAD

**Issue by SteveDCronin** [acmacalister/jetfire#63]
new to GitHub so maybe not the right avenue for this...

I was surprised when I compiled on Xcode 8.3.2 and got a warning.

JFRWebSocket.m -dequeueWrite:withCode: line 36
            SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);

Normally a warning doesn't throw me but the text of this was onerous enough that I thought I would report it..  "...Ignoring return value of function declared with 'warn_unused_result' attribute"

Perhaps the code could or should be refactored to avoid this warning?

Steve

**Comment by acmacalister** [comment]
This should be fixed in master now.
