### ISSUE TITLE
Timeout to close web-socket

### ISSUE THREAD

**Issue by Hersir88** [acmacalister/jetfire#66]
I wanted to close web-socket if some timeout is elapsed and no ping was received from server, but there is no listener for ping received, is there other mechanisms how to close web-socket on client if server dies?

**Comment by Supertecnoboff** [comment]
Couldn't you just setup your own ```NSTimer``` that checks to see if any data was returned after say 60 seconds? If data is present, then continue as normal, otherwise simple call: ```[self.socket disconnect];```.

**Comment by acmacalister** [comment]
The socket will get disconnected after the server stop responding to pings. The timeout is generally set on the server side. If you want to disconnect earlier for reason, I would use a Timer like @Supertecnoboff suggested.

**Comment by ashutosh-foodpanda** [comment]
How can I setup the timeout for connection? Any property in project or something else?
