### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by walteryaron** [acmacalister/jetfire#7]
How to set timeout ?

**Comment by daltoniam** [comment]
Currently there isn't a way to set a timeout. Is the desired use case to be a timeout like in an HTTP request?

**Comment by walteryaron** [comment]
Yes.
But for now i manage to solve the problem.
Thanks.

**Comment by daltoniam** [comment]
Cool. Glad to hear you got it figured out. I will look into what it would take to make add timeout functionally.
