### ISSUE TITLE
Keep alive? Ping and pong?

### ISSUE THREAD

**Issue by kevinrenskers** [acmacalister/jetfire#8]
Great project, it was really easy to add websockets support to an app I'm currently building. However, the socket connection always disconnects after one minute. Is there an easy way to keep the connection open, or do I need to keep a timer myself to send ping messages every 30 seconds or so? Or is the server supposed to send these ping/pong messages every once in a while?

**Comment by kevinrenskers** [comment]
Never mind, it seems that the server should send these periodically to the client if I'm not mistaken?

**Comment by daltoniam** [comment]
The WebSocket server should send a ping every so often to keep the underlining TCP socket stimulated. jetfire already responds to pings with pongs, shouldn't have to do anything. I would take a look at the WebSocket server and see why it isn't sending the pings to keep the connection alive.

**Comment by kevinrenskers** [comment]
Yep, server isn't sending them. Thanks!
